import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const faqs = [
  {
    question: "Is QRGenius really free forever?",
    answer:
      "Yes! QRGenius is 100% free with no hidden costs, no premium tiers, and no limits on how many QR codes you can create. We believe everyone should have access to quality QR code generation tools.",
  },
  {
    question: "What data do you store?",
    answer:
      "None. All QR code generation happens directly in your browser (client-side). We don't store, track, or have access to any of the content you encode. Your recent QR codes are stored locally in your browser using LocalStorage, and you can delete them anytime.",
  },
  {
    question: "What formats can I encode?",
    answer:
      "QRGenius supports URLs, plain text, WiFi credentials (WPA/WEP), vCard contact information, geographic locations, email addresses, phone numbers, SMS messages, and more. If it's text-based, you can create a QR code for it.",
  },
  {
    question: "Will my QR codes work on all devices?",
    answer:
      "Yes! QR codes are a universal standard. Any modern smartphone camera or QR code scanner app can read the codes generated by QRGenius. We use industry-standard error correction to ensure reliability.",
  },
  {
    question: "What's the maximum content size?",
    answer:
      "QR codes can encode up to about 3,000 characters, but we recommend keeping content under 1,000 characters for best scanning reliability. Longer content requires smaller modules which may be harder to scan from a distance.",
  },
  {
    question: "Can I add a logo to my QR code?",
    answer:
      "Yes! You can upload a PNG, JPG, or SVG logo (up to 1MB). The logo will be centered and scaled to 20% of the QR code size. We recommend using a simple logo with good contrast for best results. Using High error correction is recommended when adding logos.",
  },
  {
    question: "What download formats are available?",
    answer:
      "You can download your QR codes as PNG or SVG files. PNG is great for web use and printing, while SVG is perfect for high-quality printing at any size since it's vector-based.",
  },
  {
    question: "Is this GDPR compliant?",
    answer:
      "Yes. Since we don't collect, store, or process any personal data, QRGenius is fully GDPR compliant. All processing happens in your browser, and we use no cookies or tracking scripts.",
  },
];

export default function FAQ() {
  return (
    <section id="faq" className="py-16 md:py-24 bg-muted/30">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold text-foreground mb-4">
            Frequently Asked Questions
          </h2>
          <p className="text-lg text-muted-foreground">
            Everything you need to know about QRGenius
          </p>
        </div>

        <Accordion type="single" collapsible className="w-full">
          {faqs.map((faq, index) => (
            <AccordionItem
              key={index}
              value={`faq-${index}`}
              className="bg-background border border-border rounded-lg mb-3 px-4"
              data-testid={`accordion-faq-${index}`}
            >
              <AccordionTrigger className="text-left hover:no-underline py-4">
                <span className="font-medium text-foreground">{faq.question}</span>
              </AccordionTrigger>
              <AccordionContent className="text-muted-foreground pb-4">
                {faq.answer}
              </AccordionContent>
            </AccordionItem>
          ))}
        </Accordion>
      </div>
    </section>
  );
}
